# Generated by Django 5.1.6 on 2025-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_auth", "0003_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp_code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("otp", models.IntegerField()),
            ],
        ),
    ]
