# Generated by Django 5.1.6 on 2025-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_side", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="t",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
